# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 320)
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(30, 30, 100, 20))
        self.label_name.setText("Student name:")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(130, 30, 140, 20))
        self.label_attempts = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_attempts.setGeometry(QtCore.QRect(30, 60, 100, 20))
        self.label_attempts.setText("No. of attempts:")
        self.attemptsEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.attemptsEdit.setGeometry(QtCore.QRect(130, 60, 140, 20))
        self.scoreLabels = []
        self.scoreEdits = []
        for i in range(4):
            lbl = QtWidgets.QLabel(parent=self.centralwidget)
            lbl.setGeometry(QtCore.QRect(30, 100 + i * 30, 80, 20))
            lbl.setText(f"Score {i + 1}:")
            lbl.hide()
            edt = QtWidgets.QLineEdit(parent=self.centralwidget)
            edt.setGeometry(QtCore.QRect(130, 100 + i * 30, 140, 20))
            edt.hide()
            self.scoreLabels.append(lbl)
            self.scoreEdits.append(edt)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 100, 30))
        self.pushButton.setText("SUBMIT")
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(30, 290, 240, 20))
        self.resultLabel.setText("")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grader"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
